version: '3'
volumes:
  mongo-1:
    driver: local
  mongo-2:
    driver: local
  mongo-3:
    driver: local

services:
  mongo_1:
    image: mongo:4.4.3
    volumes:
     - mongo-1:/data/db
    ports:
     - "27017:27017"
    #environment:
    #  - MONGO_INITDB_ROOT_USERNAME=root
    #  - MONGO_INITDB_ROOT_PASSWORD=password
    #  - MONGO_INITDB_DATABASE=student
    networks:
      mango:

  mongo_2:
    image: mongo:4.4.3
    volumes:
     - mongo-2:/data/db
    ports:
     - "27018:27017"
    #environment: 
    #  - MONGO_INITDB_ROOT_USERNAME=root
    #  - MONGO_INITDB_ROOT_PASSWORD=password
    #  - MONGO_INITDB_DATABASE=class
    networks:
      mango:
  
  mongo_3:
    image: mongo:4.4.3
    volumes:
     - mongo-3:/data/db
    ports:
     - "27019:27017"
    #environment: 
    #  - MONGO_INITDB_ROOT_USERNAME=root
    #  - MONGO_INITDB_ROOT_PASSWORD=password
    #  - MONGO_INITDB_DATABASE=class
    networks:
      mango:

networks:
  mango: