server:
  port: 8081

eureka:
  client:
    enabled: true
    fetch-registry: true
    healthcheck:
      enabled: true
    service-url:
      defaultzone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  application:
    name: STUDENT-SERVICE

  data:
    mongodb:
      host: localhost
      port: 27019
#      username: user
#      password: password
      database: student
    rest:
      base-path: /student
 
management:
  endpoints:
    web:
      exposure:
        include: "*"
