server:
  port: 8082

eureka:
  client:
    enabled: true
    fetch-registry: true
    service-url:
      defaultzone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  application:
    name: CLASS-SERVICE

  data:
    mongodb:
      host: localhost
      port: 27018
#      username: user
#      password: password
      database: class_details
    rest:
      base-path: /class
 
  boot:
    admin:
      client:
        url:
        - http://localhost:9090
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
